# Generated by Django 5.0 on 2024-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_api_app', '0002_walletuser_date_created_alter_walletuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTNTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('bundle_volume', models.FloatField(default=0)),
                ('status', models.CharField(default='Undelivered', max_length=200)),
                ('batch_id', models.CharField(default='Unknown', max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
